version: 2.1
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: 
      name: terraform/default
      tag: "1.3.4"
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          type: approval
          path: .
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
